# Generated by Django 4.1.2 on 2022-11-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_commentsposts_delete_postscomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commentsposts',
        ),
    ]
