# Generated by Django 4.1.2 on 2022-11-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventDate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='eventOrganizer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventDesc',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventTopic',
            field=models.CharField(default='', max_length=300),
        ),
    ]
