# Generated by Django 4.1.2 on 2022-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogcontent',
            field=models.CharField(max_length=3000, unique=True),
        ),
    ]
