# Generated by Django 4.1.2 on 2022-11-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogs_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
