# Generated by Django 4.1.2 on 2022-11-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blogs_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogcontent',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blogtopic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='blogcomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentauthor', models.CharField(max_length=200)),
                ('blogcontent', models.CharField(max_length=3000)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blogs')),
            ],
        ),
    ]
