# Generated by Django 4.1.2 on 2022-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dept',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='passed_out_year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
