# Generated by Django 4.1.2 on 2022-11-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=2000)),
                ('author', models.CharField(default='', max_length=100)),
                ('tag', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerauthor', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=3000)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='queries.queries')),
            ],
        ),
    ]
